[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "data_analysis"
version = "0.1.0"
authors = [
  { name="Your Name", email="your.email@example.com" },
]
description = "A Modular Data Sanitization & Exploration Engine"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pandas",
    "numpy",
    "plotly",
    "scipy",
    "scikit-learn",
    "pydantic",
    "networkx",
    "graphviz",
    "ipython"
]

[project.urls]
"Homepage" = "https://github.com/yourusername/data-analysis-tool"
